In [2]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]

data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

Q1.Get the shape of the matrix.

In [3]:
shape = data.shape
print("Shape of the data:", shape)

Shape of the data: (5, 3)


Q2. Find the average age of students.

In [9]:
age_col = data[:,0]
age_sum = np.sum(age_col)
shape_age_col = age_col.shape[0]
average_age = age_sum / shape_age_col
print("Average age:", average_age)

Average age: 18.4


Q3. Extract Math marks of all students.

In [12]:
math_marks_col = data[:,1]
print("Math marks of all Students:", math_marks_col)
print("Student 1 Math marks:", math_marks_col[0])
print("Student 2 Math marks:", math_marks_col[1])
print("Student 3 Math marks:", math_marks_col[2])
print("Student 4 Math marks:", math_marks_col[3])
print("Student 5 Math marks:", math_marks_col[4])

Math marks of all Students: [85 92 76 65 90]
Student 1 Math marks: 85
Student 2 Math marks: 92
Student 3 Math marks: 76
Student 4 Math marks: 65
Student 5 Math marks: 90


Q4. Find the highest Science mark.

In [20]:
science_marks_col = data[:,2]
highest_science_marks = np.max(science_marks_col)
print("Highest Science marks:", highest_science_marks)
highest_science_marks_index = np.argmax(science_marks_col)
print("Student with highest Science marks is Student", highest_science_marks_index + 1)

Highest Science marks: 95
Student with highest Science marks is Student 3


Q5. Get details of the student who scored more than 90 in Math.

In [23]:
more_than_90_maths = math_marks_col > 90
print("Students with more than 90 marks in Math:", math_marks_col[more_than_90_maths])

Students with more than 90 marks in Math: [92]


Q6. Increase Math marks of all students by 5.

In [24]:
increase_by_5 = math_marks_col + 5
print("Math marks after increasing by 5:", increase_by_5)

Math marks after increasing by 5: [90 97 81 70 95]


Q7. Find how many students are younger than 19.

In [26]:
younger_than_19 = age_col < 19
print("Students younger than 19:", age_col[younger_than_19])

Students younger than 19: [18 17 18]


Q8. Calculate the average marks in each subject (column-wise mean).

In [27]:
avg_in_maths = np.mean(math_marks_col)
avg_in_science = np.mean(science_marks_col)
print("Average marks in Math:", avg_in_maths)
print("Average marks in Science:", avg_in_science)

Average marks in Math: 81.6
Average marks in Science: 83.2


Q9. Get data of students who scored at least 80 in both subjects.

In [33]:
less_than_80_science = science_marks_col < 80
less_than_80_maths = math_marks_col < 80
both = less_than_80_science & less_than_80_maths
students_index = np.where(both)[0]
for index in students_index:
    print("Student", index + 1, "has less than 80 marks in both subjects.")

Student 4 has less than 80 marks in both subjects.


Q10. Replace all Science marks less than 75 with 0.

In [37]:
less_that_75_both = (math_marks_col < 75) & (science_marks_col < 75)
students_index = np.where(less_that_75_both)[0]
data[students_index, 1:] = 0
print("Data after setting marks to 0 for students with less than 75 marks in both subjects:")
print(data)

Data after setting marks to 0 for students with less than 75 marks in both subjects:
[[18 85 78]
 [19 92 88]
 [17 76 95]
 [18  0  0]
 [20 90 85]]
