Arithmetic Operations

In [1]:
import numpy as np

In [6]:
a1 = np.random.randint(1, 11, 5)
a2 = np.random.randint(1, 11, 5)

In [7]:
print(a1)
print(a2)

[ 1 10  4  9  1]
[ 5  6  2 10  4]


In [9]:
add = a1 + a2
add

array([ 6, 16,  6, 19,  5], dtype=int32)

In [10]:
substraction = a1 - a2
substraction

array([-4,  4,  2, -1, -3], dtype=int32)

In [11]:
power = a1 ** a2
power

array([         1,    1000000,         16, -808182895,          1],
      dtype=int32)

In [12]:
multiplication = a1 * a2
multiplication

array([ 5, 60,  8, 90,  4], dtype=int32)

In [13]:
divison = a1 / a2
divison

array([0.2       , 1.66666667, 2.        , 0.9       , 0.25      ])

In [14]:
floor_division = a1 // a2
floor_division

array([0, 1, 2, 0, 0], dtype=int32)

BroadCasting

In [15]:
print(a1)

[ 1 10  4  9  1]


In [16]:
arr1 = np.array(a1);
arr1

array([ 1, 10,  4,  9,  1], dtype=int32)

In [17]:
arr1 + 10


array([11, 20, 14, 19, 11], dtype=int32)

Deep Copy and Shallow Copy

In [18]:
arr = np.arange(1, 11)
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
slice = arr[0:5]
slice = slice + 10
slice

array([11, 12, 13, 14, 15])

In [20]:
a = arr
a[0] = 99
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
b = arr.copy()
b[0] = 100
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [24]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Matrix Operations

In [27]:
mat1 = np.random.randint(1, 11, (3, 3))
mat2 = np.random.randint(1, 11, (3, 3))

In [28]:
print(mat1)

[[ 9  7  4]
 [ 8 10  7]
 [ 3  8  7]]


In [29]:
print(mat2)

[[3 2 5]
 [9 6 9]
 [3 4 9]]


In [30]:
mat_multiplication = mat1 @ mat2
print(mat_multiplication)

[[102  76 144]
 [135 104 193]
 [102  82 150]]


In [32]:
mat_multiplication = np.dot(mat1, mat2)
print(mat_multiplication)

[[102  76 144]
 [135 104 193]
 [102  82 150]]


In [35]:
transpose = mat_multiplication.T
print(transpose)

[[102 135 102]
 [ 76 104  82]
 [144 193 150]]


Advance Array Manipulations

Array Stacking

In [42]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])


In [46]:
vertical_stacked = np.vstack((arr1, arr2, arr3))
print(vertical_stacked)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
horizontal_stacked = np.hstack((arr1, arr2, arr3))
print(horizontal_stacked)

[1 2 3 4 5 6 7 8 9]


In [43]:
stacked = np.stack((arr1, arr2, arr3), axis=0)
print(stacked)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
stacked = np.stack((arr1, arr2, arr3), axis=1)
print(stacked)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [45]:
stacked = np.stack((arr1, arr2), axis=1)
print(stacked)

[[1 4]
 [2 5]
 [3 6]]


vertical splitting

In [48]:
mat = np.random.randint(1, 11, (3, 3))
print(mat)

[[2 2 8]
 [9 7 2]
 [2 8 7]]


In [49]:
vertical_split = np.vsplit(mat, 3)
print(vertical_split)

[array([[2, 2, 8]], dtype=int32), array([[9, 7, 2]], dtype=int32), array([[2, 8, 7]], dtype=int32)]


In [51]:
horizontal_split = np.hsplit(mat, 3)
print(horizontal_split)

[array([[2],
       [9],
       [2]], dtype=int32), array([[2],
       [7],
       [8]], dtype=int32), array([[8],
       [2],
       [7]], dtype=int32)]
