In [3]:
import numpy as np

Numpy Indexing and slicing of vectors

In [4]:
arr = np.arange(1,11)

In [5]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(arr[9])

10


In [7]:
print(arr[2:7])
print(arr[:5])
print(arr[5:])
print(arr[:])

[3 4 5 6 7]
[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


Matix Indexing and slicing

In [8]:
arr = np.arange(1,31).reshape(5,6)
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [9]:
print(arr[0:2,2:4])

[[ 3  4]
 [ 9 10]]


In [11]:
print(arr[2:,4:])

[[17 18]
 [23 24]
 [29 30]]


In [21]:
print(arr[:,3])

[ 4 10 16 22 28]


In [22]:
print(arr[2,:])

[13 14 15 16 17 18]


Boolean Indexing

In [23]:
print(arr)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [24]:
bool_index = arr % 2 == 0
print(bool_index)

[[False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]
 [False  True False  True False  True]]


In [25]:
arr_even = arr[bool_index]
print(arr_even)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]
