In [3]:
import numpy as np

Array Creation

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
list = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
arr2 = np.array(list)

In [7]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Generation Function

In [8]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [9]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Random Array Generation Functions 

In [13]:
np.random.rand(10)

array([0.4390127 , 0.7794765 , 0.16573823, 0.63690697, 0.14655888,
       0.49249037, 0.94484511, 0.59289193, 0.10368082, 0.52025136])

In [14]:
np.random.randn(100)

array([-0.20728382, -0.26322833,  0.85643157,  0.90484954,  1.01053958,
        0.56006899, -0.31152322, -0.82063054,  1.16808434, -0.75428615,
       -1.64568884, -0.89306373,  0.13835385,  0.47051332, -0.59016825,
       -0.61462648, -1.6882636 ,  0.47679922, -0.24281321,  0.52098067,
       -2.38991729,  0.0129596 ,  1.11925806,  0.46067533, -0.93236377,
        0.08222123,  1.44644922,  0.64068031,  0.10686405,  0.42167335,
       -0.18863119, -0.54306738, -0.83855149, -0.187802  ,  1.66834884,
       -0.84519576, -0.341246  ,  0.4603485 , -3.98407293,  0.28942061,
        1.39301948, -1.46212453,  0.88137068,  1.78072375,  0.48653389,
       -0.16477022, -0.63491271,  0.36267847, -0.84442981,  1.8025093 ,
        0.30894962,  0.79092998, -0.64620134, -0.10209669,  0.96365487,
        1.98290954,  0.12020233, -0.5714731 , -0.73306753, -0.78132418,
       -0.59276912,  0.85751371,  1.52219686,  1.53310068,  1.22474964,
        0.15165905,  1.37699887,  0.29071384, -1.50927213, -0.59

In [15]:
np.random.randint(1,100,20)

array([73, 65, 95, 17, 96, 55, 85,  9,  1, 16, 93, 50, 66, 64, 69, 35, 34,
       74, 12, 97], dtype=int32)

In [16]:
np.random.randint(1,100,(4,4))

array([[88, 59,  9, 55],
       [46, 63, 49, 46],
       [61, 81,  5, 60],
       [ 2, 41, 50, 63]], dtype=int32)

Numpy Array Attributes


In [17]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr.size

9

In [20]:
arr.ndim


2

In [21]:
arr.shape

(3, 3)

In [22]:
arr.dtype

dtype('int64')

In [23]:
arr.ctypes

In [24]:
arr.nbytes

72

In [25]:
arr.itemsize

8

In [26]:
arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Numpy Array Methods


In [27]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.max()

np.int64(9)

In [29]:
arr.min()

np.int64(1)

In [30]:
arr.sum()

np.int64(45)

In [31]:
np.sum(arr,axis=0)

array([12, 15, 18])

In [32]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [33]:
arr.mean()

np.float64(5.0)

In [34]:
arr.std()

np.float64(2.581988897471611)

In [35]:
arr.argmax()

np.int64(8)

In [36]:
arr.argmin()

np.int64(0)

Reshaping and Resizing

In [37]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
arr.reshape(9)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
arr2 = np.arange(1,31)

In [41]:
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [44]:
reshaped_arr = arr2.reshape((5,6))

In [45]:
reshaped_arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])