In [11]:
import numpy as np

Numpy Indexing and slicing of vectors

In [12]:
arr = np.arange(1,11)

In [13]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
print(arr[9])

10


In [15]:
print(arr[2:7])
print(arr[:5])
print(arr[5:])
print(arr[:])

[3 4 5 6 7]
[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
