In [1]:
import numpy as np

Array Creation

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
list = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
arr2 = np.array(list)

In [6]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Generation Function

In [7]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

Random Array Generation Functions 

In [16]:
np.random.rand(10)

array([0.55227484, 0.41413435, 0.17945915, 0.77330253, 0.99388511,
       0.56942021, 0.44935787, 0.23402828, 0.47264909, 0.39691963])

In [17]:
np.random.randn(100)

array([-0.86206448,  1.19935452, -0.24661435,  1.17645706,  1.64827494,
       -0.37923757,  1.30547226, -0.76437494, -0.9938584 , -0.08573459,
        1.49508176,  0.6537791 ,  0.92862231, -0.70650663, -1.89038154,
        0.4703284 , -1.50492355, -1.65138802, -0.01225124,  1.02202061,
       -0.51173555,  0.60200453, -0.99737135, -0.51103547,  0.1443742 ,
       -0.53372899,  0.67618224,  0.34724416,  0.74527684, -1.72764279,
        0.12307007, -0.25921108,  1.32850725,  0.12835261,  0.38954509,
       -0.46857834,  0.42124364,  0.24219085,  0.74694097, -0.28622135,
        0.97566986, -0.55467612,  0.48335713, -0.33162668,  1.00818151,
       -1.89116651,  1.84176029, -1.29482478, -0.13942569, -0.6104162 ,
       -0.20583009, -0.81808714,  0.37532081, -0.73203221,  0.90450143,
        1.59897423,  0.51246113,  0.54660484, -0.73766203,  1.07719938,
        0.5466292 , -0.36605084,  1.01590816, -0.23739208,  1.37500269,
       -0.04075683, -0.30581937,  1.65114367, -0.54771533, -0.04

In [20]:
np.random.randint(1,100,20)

array([16, 42, 42, 78, 77, 57, 70, 17, 43, 22, 90, 58, 57, 80, 55, 67, 62,
        3, 58, 14], dtype=int32)