In [1]:
import numpy as np

Array Creation

In [2]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
list = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
arr2 = np.array(list)

In [6]:
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Array Generation Function

In [7]:
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])